services:
  postgres:
    image: postgres:17.6-alpine3.21
    container_name: postgres_dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_dev
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.16
    container_name: meilisearch_dev
    ports:
      - "127.0.0.1:7700:7700"
    restart: always
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=production
    volumes:
      - meilisearch_data_dev:/meili_data
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
        interval: 5s
        timeout: 3s
        retries: 5

  manager:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/vvip-kitchen/boo-manager:latest
    container_name: manager_dev
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - MANAGER_API_TOKEN=${MANAGER_API_TOKEN}

volumes:
  postgres_data_dev:
  redis_data_dev:
  meilisearch_data_dev:
