import meilisearch
from datetime import datetime
from typing import List, Optional
from utils.config import MEILI_MASTER_KEY


class MeilisearchService:
  def __init__(self, host="http://meilisearch:7700"):
    self.client = meilisearch.Client(host, MEILI_MASTER_KEY)
    self.index_name = "boo"
    self._init_index()

  def _init_index(self):
    """Init index with config"""
    try:
      self.index = self.client.get_index(self.index_name)
    except:
      self.client.create_index(self.index_name, {"primaryKey": "image_id"})
      self.index = self.client.index(self.index_name)

    self.index.update_settings(
      {
        "searchableAttributes": [
          "vlm_caption",
          "user_caption",
          "author_name",
          "server_name",
        ],
        "sortableAttributes": ["created_at"],
        "filterableAttributes": ["created_at", "server_id", "author_id", "channel_id"],
        "embedders": {
          "image": {"source": "userProvided", "dimensions": 1024},
          "vlm_caption": {"source": "userProvided", "dimensions": 1024},
          "user_caption": {"source": "userProvided", "dimensions": 1024},
        },
      }
    )

  def add_document(
    self,
    image_id: str,
    image_embedding: List[float],
    vlm_caption: str,
    vlm_caption_embedding: List[float],
    user_caption: Optional[str] = None,
    user_caption_embedding: Optional[List[float]] = None,
    # Discord-specific metadata
    message_url: Optional[str] = None,
    message_id: Optional[str] = None,
    server_id: Optional[str] = None,
    server_name: Optional[str] = None,
    channel_id: Optional[str] = None,
    channel_name: Optional[str] = None,
    author_id: Optional[str] = None,
    author_name: Optional[str] = None,
    attachment_url: Optional[str] = None,
    metadata: Optional[dict] = None,
  ):
    """
    Add image document with embeddings and Discord metadata.

    Args:
        image_id: Unique identifier for the image
        image_embedding: Image embedding vector
        vlm_caption: Caption generated by VLM
        vlm_caption_embedding: VLM caption embedding vector
        user_caption: Optional user-provided caption
        user_caption_embedding: Optional user caption embedding vector
        message_url: Discord message URL for easy reference
        message_id: Discord message ID
        server_id: Discord server/guild ID
        server_name: Discord server name
        channel_id: Discord channel ID
        channel_name: Discord channel name
        author_id: Discord user ID who sent the image
        author_name: Discord username
        attachment_url: Original Discord attachment URL
        metadata: Optional additional metadata
    """
    document = {
      "image_id": image_id,
      "_vectors": {"image": image_embedding, "vlm_caption": vlm_caption_embedding},
      "vlm_caption": vlm_caption,
      "created_at": datetime.utcnow().isoformat(),
    }

    # Add user caption if provided
    if user_caption and user_caption_embedding:
      document["_vectors"]["user_caption"] = user_caption_embedding
      document["user_caption"] = user_caption

    # Add Discord metadata
    if message_url:
      document["message_url"] = message_url
    if message_id:
      document["message_id"] = message_id
    if server_id:
      document["server_id"] = server_id
    if server_name:
      document["server_name"] = server_name
    if channel_id:
      document["channel_id"] = channel_id
    if channel_name:
      document["channel_name"] = channel_name
    if author_id:
      document["author_id"] = author_id
    if author_name:
      document["author_name"] = author_name
    if attachment_url:
      document["attachment_url"] = attachment_url

    # Add any additional metadata
    if metadata:
      document.update(metadata)

    return self.index.add_documents([document])

  def update_document(self, image_id, **fields):
    """Update specific fields of a document"""
    document = {"image_id": image_id, **fields}
    return self.index.update_documents([document])

  def delete_document(self, image_id):
    """Delete a document by ID"""
    return self.index.delete_document(image_id)

  def search(
    self,
    query: str,
    query_embedding: List[float],
    embedder: str = "image",
    semantic_ratio: float = 0.5,
    limit: int = 20,
    filter: Optional[str] = None,
  ):
    """Hybrid search with vector and keyword"""
    search_params = {
      "hybrid": {"semanticRatio": semantic_ratio, "embedder": embedder},
      "vector": query_embedding,
      "limit": limit,
      "showRankingScore": True,
    }

    if filter:
      search_params["filter"] = filter

    return self.index.search(query, search_params)

  def get_document(self, image_id):
    """Get document by ID"""
    return self.index.get_document(image_id)

  def delete_all_documents(self):
    """Delete all documents from index"""
    return self.index.delete_all_documents()
