name: Deploy Embeddings API to Modal

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install dependencies
      working-directory: ./embeddings
      run: |
        uv pip install --system modal torch numpy Pillow torchvision sentence-transformers fastapi[standard]
        if [ -f pyproject.toml ]; then
          uv sync
        fi

    - name: Authenticate with Modal
      env:
        MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
        MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      run: |
        modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET

    - name: Deploy to Modal
      working-directory: ./embeddings
      run: |
        echo "🚀 Deploying embeddings API to Modal..."
        modal deploy main.py

    - name: Get deployment URL
      working-directory: ./embeddings
      run: |
        echo "📡 Getting deployment URL..."
        modal app list

    - name: Health check
      run: |
        echo "🏥 Waiting for deployment to be ready..."
        sleep 30  # Give deployment time to start

    - name: Notify success
      if: success()
      run: |
        echo "✅ Deployment successful!"
        echo "🔗 Your API is live at: https://kashifulhaque--boo-embeddings-api-fastapi-app.modal.run/docs"

    - name: Notify failure
      if: failure()
      run: |
        echo "❌ Deployment failed!"
        echo "Check the logs above for details."
